name: Build and Publish to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-crawl-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install & deploy
        run: |
          npm i
          npm run deploy
